### model
model_name_or_path: ../llama3.1-8B-instruct
#adapter_name_or_path: saves/llama3.1-8B-Monitor-Tuning/lora/MT_pcgrad/

### method
stage: sft
do_predict: true
finetuning_type: full # lora, full

### dataset
eval_dataset: gsm-8k_test_5shot_cot  # ARC-Challenge-Test-InstructFormat, natural_instructions_test, gsm-8k_test_InstructFormat , natural_instructions_eval
template: llama3
cutoff_len: 2048
max_samples: 50000
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: saves/predictions/gsm-8k_test_5shot_cot/llama3.1-8B-MT_pcgrad # natural_instructions_test/ ARC-Challange/
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 5
predict_with_generate: true
ddp_timeout: 180000000
